# Generated by Django 5.0.8 on 2024-09-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptography_app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='text',
            new_name='quote',
        ),
    ]
